<?php
session_start();

if (!isset($_SESSION['loggedin']) || $_SESSION['loggedin'] !== true) {
    header("Location: index.php");
    exit();
}

require_once 'includes/data.php';
require_once 'includes/header.php';

$view_id = isset($_GET['id']) ? (int)$_GET['id'] : null;
$msg = '';


//joining an already existing group using the invite code that is generated by nat
if ($_SERVER['REQUEST_METHOD'] === 'POST') {

    if (isset($_POST['invite_code'])) {
        $result = rmq_rpc('group.join', [
            'invite_code' => strtoupper(trim($_POST['invite_code'])),
            'username' => $_SESSION['username'],
        ]);
        if ($result['success'] ?? false ) {
            $name = htmlspecialchars($result['group_name']);
            $code = htmlspecialchars($result['group_id']);
            $msg= 'success:You have joined the circle. Welcome!!!';
        }
        else {
            $msg= 'error:'.($result['message'] ?? 'Invalid invite code. Please check and try again.');     
        }
    }


    if (isset($_POST['create_group'])) {
        $result = rmq_rpc('group.create', [
            'name' => trim($_POST['group_name']),
            'group_desc' => trim($_POST['group_desc']),
            'username' => $_SESSION['username'],
        ]);
        if ($result['success'] ?? false) {
            $name = htmlspecialchars($result['group_name']);
            $code = htmlspecialchars($result['invite_code']);
            $msg  = "success:Circle <em>$name</em> created! Your invite code is: <strong>$code</strong>";
        } else {
            $msg = 'error:Could not create circle. Please try again.';
        }
    }
}

list($msg_type, $msg_text) = $msg ? explode(':', $msg, 2) : ['', ''];


if ($view_id) {
    $group_res = rmq_rpc('group.get', [
        'group_id' => $view_id,
        'username' => $_SESSION['username'],
    ]);
    $group = $group_res['group'] ?? null;
    if ($group) {
        $current_book = getBookById((int)($group['current_book_id']));
        $disc_res = rmq_rpc('discussion.list', [
            'group_id' => $view_id,
            'username' => $_SESSION['username'],
        ]);
        $group_discussions = $disc_res['discussions'];
        $sched_res      = rmq_rpc('schedule.list', [
            'group_id' => $view_id,
            'username' => $_SESSION['username'],
        ]);
        $group_schedule = $sched_res['events'];
        $gbooks_res  = rmq_rpc('group.books', [
            'group_id' => $view_id,
            'username' => $_SESSION['username'],
        ]);
        $group_books = $gbooks_res['books'];
        $gathering_count  = count($group_schedule);
        $discussion_count = count($group_discussions);
    }

    $tab = $_GET['tab'] ?? 'discuss';

} else {
    $all_groups_res = rmq_rpc('group.list', [
        'username' => $_SESSION['username'],
    ]);

    $groups = $all_groups_res['groups'];

    $bselect_res = rmq_rpc('book.list', [
        'fields' => 'id,title',
        'username' => $_SESSION['username'],
    ]);

    $books_for_select = $bselect_res['books'];
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Noetic — Groups</title>
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,600;1,300;1,400&family=IM+Fell+English:ital@0;1&family=Crimson+Text:ital,wght@0,400;0,600;1,400&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">   
    <link rel="stylesheet" href="styles.css">
</head>
<body>
<?php if ($msg_text): ?>
    <div class="alert alert-<?php echo $msg_type === 'success' ? 'success' : 'danger'; ?>">
        <?php echo $msg_text; ?>
    </div>
<?php endif; ?>

<?php if ($view_id): ?>

    <?php if (!$group): ?>
        <p style="color:var(--text-muted); font-style:italic;">Circle not found.</p>
    <?php else: ?>

    <div style="font-size:0.8rem; color:var(--text-muted); margin-bottom:1.5rem;">
        <a href="groups.php" style="color:var(--umber); text-decoration:none;">Circles</a>
        &nbsp;›&nbsp; <?php echo htmlspecialchars($group['name']); ?>
    </div>

    <!--book widgets that should be showing up but aren't when you join-->
    <div class="row g-4">
        <div class="col-lg-8">
            <h2 class="page-heading"><?php echo htmlspecialchars($group['name']); ?></h2>
            <p style="color:var(--text-muted); font-style:italic; margin-bottom:1rem;">
                <?php echo htmlspecialchars($group['description']); ?>
            </p>

            <div class="mb-3 d-flex flex-wrap gap-2">
                <?php foreach ($group['members'] as $m): ?>
                <span class="member-pill">
                    <span style="width:20px;height:20px;border-radius:50%;background:var(--moss);display:flex;align-items:center;justify-content:center;font-size:0.65rem;">
                        <?php echo strtoupper(substr($m, 0, 1)); ?>
                    </span>
                    <?php echo htmlspecialchars($m); ?>
                </span>
                <?php endforeach; ?>
                <span class="member-pill" style="cursor:pointer; border-style:dashed;"
                      data-bs-toggle="modal" data-bs-target="#inviteModal">
                    <i class="bi bi-plus"></i> Invite
                </span>
            </div>

            <div class="tab-nav">
                <a href="?id=<?php echo $view_id; ?>&tab=discuss"  class="tab-link <?php echo $tab === 'discuss'  ? 'active' : ''; ?>">Discussion Board</a>
                <a href="?id=<?php echo $view_id; ?>&tab=schedule" class="tab-link <?php echo $tab === 'schedule' ? 'active' : ''; ?>">Gatherings</a>
                <a href="?id=<?php echo $view_id; ?>&tab=members"  class="tab-link <?php echo $tab === 'members'  ? 'active' : ''; ?>">Members</a>
            </div>
        </div>
    </div>

    <?php endif; ?>

<?php else: ?>

<div class="d-flex justify-content-between align-items-end mb-4">
    <h2 class="page-heading mb-0">Reading Circles</h2>
    <button class="btn-n btn" data-bs-toggle="modal" data-bs-target="#createModal">
        <i class="bi bi-plus-lg"></i> New Circle
    </button>
</div>

<div class="n-card p-4 mb-4">
    <h6 style="font-family:'IM Fell English',serif; margin-bottom:0.8rem;">Join a Circle</h6>
    <form method="post" class="d-flex gap-2">
        <input type="text" class="form-control" name="invite_code"
               placeholder="Enter invite code (e.g. OBS-7X2K)"
               style="max-width:300px; letter-spacing:0.15em; text-transform:uppercase;">
        <button type="submit" class="btn-n btn">Join</button>
    </form>
</div>

<div class="row g-4">
    <?php foreach ($groups as $g):
        $cb        = getBookById((int)($g['current_book_id'] ?? 0));
        $is_member = in_array($_SESSION['username'], $g['members'] ?? []);
    ?>
    <div class="col-md-6 col-lg-4">
        <div class="n-card p-4 h-100" style="position:relative;">
            <?php if ($is_member): ?>
            <span class="n-badge" style="position:absolute; top:1rem; right:1rem;">Member</span>
            <?php endif; ?>
            <h5 style="font-family:'IM Fell English',serif; margin-bottom:0.3rem;">
                <?php echo htmlspecialchars($g['group_name']); ?>
            </h5>
            <p style="font-size:0.9rem; color:var(--text-muted); font-style:italic; margin-bottom:1rem;">
                <?php echo htmlspecialchars($g['group_desc'] ?? $g['description']); ?>
            </p>
            <?php if ($cb): ?>
            <div class="d-flex gap-3 align-items-center mb-3">
                <img src="<?php echo htmlspecialchars($cb['cover']); ?>"
                     style="width:44px;height:66px;object-fit:cover;border:1px solid rgba(134,113,91,0.3);border-radius:1px;" alt="">
                <div>
                    <div style="font-size:0.75rem; text-transform:uppercase; letter-spacing:0.08em; color:var(--text-muted);">Reading Now</div>
                    <div style="font-style:italic; font-size:0.95rem;"><?php echo htmlspecialchars($cb['title']); ?></div>
                    <div style="font-size:0.8rem; color:var(--text-muted);"><?php echo htmlspecialchars($cb['author']); ?></div>
                </div>
            </div>
            <?php endif; ?>
            <div class="d-flex align-items-center justify-content-between">
                <div style="font-size:0.82rem; color:var(--text-muted);">
                    <i class="bi bi-people"></i> <?php echo $g['member_count'] ?? 0; ?> members
                </div>
                <a href="groups.php?id=<?php echo $g['group_id']; ?>" class="btn-n-outline btn btn-sm">Enter Circle</a>
            </div>
        </div>
    </div>
    <?php endforeach; ?>
    <?php if (empty($groups)): ?>
    <div class="col-12 text-center" style="color:var(--text-muted); padding:3rem; font-style:italic;">
        No circles found. Create one or join with an invite code.
    </div>
    <?php endif; ?>
</div>

<div class="modal fade" id="createModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content" style="background:var(--card); border:1px solid rgba(134,113,91,0.3); border-radius:4px;">
            <div class="modal-header" style="border-bottom:1px solid rgba(134,113,91,0.2);">
                <h5 class="modal-title" style="font-family:'IM Fell English',serif; color:var(--blush);">Found a New Circle</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <form method="post">
                    <input type="hidden" name="create_group" value="1">
                    <div class="mb-3">
                        <label class="form-label">Circle Name</label>
                        <input type="text" class="form-control" name="group_name" placeholder="e.g. The Somnambulist Society" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Description</label>
                        <textarea class="form-control" name="group_desc" rows="3" placeholder="What does your circle read?"></textarea>
                    </div>
                    <button type="submit" class="btn-n btn w-100">Create Circle</button>
                </form>
            </div>
        </div>
    </div>
</div>

<?php endif; ?>

<?php require_once 'includes/footer.php'; ?>
    </body>
</html>