#!/usr/sbin/nft -f
flush ruleset
define IF_LOOPBACK = {lo}
table inet filter {
        chain input {
                type filter hook input priority 0; 
                policy drop;
                meta iif $IF_LOOPBACK accept
                ct state established,related accept
                tcp dport {80, 443} accept # HTTP & HTTPs
                tcp dport {5672, 15672} accept # RabbitMQ
                tcp dport 22 accept # ssh

                include "/etc/nftables/input-rules.d/*.conf";
        }

        chain forward {
                type filter hook forward priority 0; policy drop;
        }

        chain output {
                type filter hook output priority 0;
        }
}
include "/etc/nftables/tables.d/*.conf";