#!/usr/sbin/nft -f
flush ruleset
define IPs = {100.101.27.73, 100.127.138.110, 100.112.153.128, 100.98.224.46,100.99.7.121,100.71.220.108}
table inet filter {
	chain input {
                type filter hook input priority 0; policy drop;
                ct state established,related accept
                iifname lo accept
                ct state invalid drop
                ip saddr $IPs tcp dport 22 accept
                tcp dport 22 reject with icmpx type admin-prohibited
                tcp dport {80, 443} accept
                ip saddr $IPs tcp dport 5672 accept
                ip protocol icmp accept
                iif lo tcp dport 3306  accept 
                tcp dport 3306 reject with icmpx type admin-prohibited
                log prefix "nftables-drop: " group 0
                drop
        }

        chain forward {
                type filter hook forward priority 0; policy drop;
        }

        chain output {
                type filter hook output priority 0; 
        }
}
